# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bW0OrvsElM89w2WbCQHLFaeFyplNRE3v
"""
import pandas as pd

def format_spei(spei_df):
  spei_df.index = spei_df['siteID']
  spei_df = spei_df.iloc[:,1:].T
  spei_df.index = pd.to_datetime(spei_df.index, format='x%Y.%m.%d')
  spei_df.index = spei_df.index.rename('date') 
  spei_df = spei_df.resample('M').mean()
  #full years only
  spei_df = spei_df.loc[(spei_df.index > '1986') & (spei_df.index < '2019')]
  return spei_df

def check_drought_year(site, spei_loc='SPEI_folder/SPEI_monthly_EBTRNsites.csv'):
  spei_df = pd.read_csv(spei_loc, parse_dates=True)
  spei_df = format_spei(spei_df)
  drought_years = []
  for idx, year in enumerate(spei_df.index.year.unique()):
    mar_2_aug = spei_df[(spei_df.index.month >= 5) & (spei_df.index.month <= 8)]
    site_df = mar_2_aug[site]
    year_df = site_df[site_df.index.year == year]
    if len(year_df[year_df < -1]) > 0:
      #print(year, 'drought')
      drought_years.append(year)
  return drought_years

def get_drought_idxs(site, spei_loc='SPEI_folder/SPEI_monthly_EBTRNsites.csv'):
  spei_df = pd.read_csv(spei_loc, parse_dates=True)
  spei_df = format_spei(spei_df)
  bps = check_drought_year(site)
  copy_df = spei_df.copy()
  copy_df['Date'] = copy_df.index
  copy_df = copy_df.reset_index()
  idxs = []

  dates=[]
  for bp in bps:
    date = spei_df.index[spei_df.index.year == bp][5]
    dates.append(date)
  
  idxs = []
  for date in dates:
    idx = copy_df[copy_df['Date'] == date].index.tolist()
    idxs.extend(idx)

  idxs.append(len(spei_df))  
  return idxs

def plot_drought_years(site):
  fig, ax = plt.subplots()
  bps = check_drought_year(site)
  for bp in bps:
    date = spei_df.index[spei_df.index.year == bp][0]
    plt.axvline(date)
  return (fig,ax)